### ISSUE TITLE
第一个ISSSSSSSUE

### ISSUE THREAD

**Issue by dreamer2q** [NekoWheel/NekoBox#1]
![image](https://user-images.githubusercontent.com/56211747/76684652-a929f880-6648-11ea-8fe6-84e19e4eb968.png)

**Comment by wuhan005** [comment]
请详细描述你遇到的问题

**Comment by dreamer2q** [comment]
表情符号发不出去，比如👍🐧。其它都OK

**Comment by wuhan005** [comment]
fixed in [commit](https://github.com/NekoWheel/NekoBox/commit/40813b79a10d47c6cc6badd471378ba2c36a080f)
