### ISSUE TITLE
个性域名可以给个实例吗，太笨了一直出错https://box.n3ko.co/_/yxrbytedance  报错个性域名只能包含字符或数字或横杠 -_

### ISSUE THREAD

**Issue by baijianruoliorz** [NekoWheel/NekoBox#10]

**Comment by wuhan005** [comment]
个性域名最长只能十位。
现已改成最长 20 位，您现在可以尝试重新注册。

**Comment by wuhan005** [comment]
你输入的是 `yxrbytedance` 还是 `box.n3ko.co/_/yxrbytedance` 这个 URL？应该是输入前者。

**Comment by baijianruoliorz** [comment]
> 你输入的是 `yxrbytedance` 还是 `box.n3ko.co/_/yxrbytedance` 这个 URL？应该是输入前者。

哇 终于好了 我输得后者，，，太笨了没看懂提示:D

**Comment by baijianruoliorz** [comment]
> 你输入的是 `yxrbytedance` 还是 `box.n3ko.co/_/yxrbytedance` 这个 URL？应该是输入前者。

谢谢回答
