### ISSUE TITLE
关于删除数据的问题

### ISSUE THREAD

**Issue by zhaojp17** [NekoWheel/NekoBox#12]
看到兔小巢上的[“吐槽反馈”](https://support.qq.com/products/293656/)暂时还没回复，想冒昧开个issue请教一下作者大大近期有无加入

1. 删除（或修改）既有回答
2. 注销账户

等删除数据的功能的计划？一方面能方便修改一些无意的笔误，另一方面能在以后回溯删除一些可能有变或不再合时宜的回答。

（真的很喜欢这个简单的界面(●'◡'●)感谢开发！顺祝新春快乐~）

**Comment by wuhan005** [comment]
很高兴收到你的反馈，感谢你喜欢 NekoBox。

抱歉兔小巢那边堆积了很多问题我一直没有去看，针对你的反馈近期我会抽时间完善一下这部分。

也祝你新春快乐。🎉

**Comment by DS587** [comment]
同期待这两个实用功能 ^ ^
