### ISSUE TITLE
老哥，网站炸了，上不去了

### ISSUE THREAD

**Issue by NAOLIU** [NekoWheel/NekoBox#14]
上不去网站了

**Comment by DS587** [comment]
我也登不上去了好哥哥😭😭😭

**Comment by wuhan005** [comment]
我说阿里云咋没给我报警，绷不住了😅
<img width="324" alt="image" src="https://user-images.githubusercontent.com/12731778/158399307-181a56e8-1e4a-43f8-a7bf-95ace4db198c.png">
