### ISSUE TITLE
提示少了一个表，是哪里忘记配置了吗

### ISSUE THREAD

**Issue by hdm9527** [NekoWheel/NekoBox#25]
![image](https://user-images.githubusercontent.com/39702328/204139711-2c19e8dd-8dee-40d9-acbf-6d7ee6a20744.png)
配置文件
![image](https://user-images.githubusercontent.com/39702328/204139796-fd652923-bfc3-401e-b2af-5e75a4c698ca.png)
数据库
![image](https://user-images.githubusercontent.com/39702328/204139806-13d868ad-7892-41f0-bb36-338dd02d7a6f.png)

**Comment by wuhan005** [comment]
这是 Flamego Session 中间件的一个老问题了。
在使用 MySQL 数据库存储 Session 时不会自动创建表，需要手动执行如下语句创建：
```sql
CREATE TABLE `sessions` (
  `key` varchar(255) NOT NULL,
  `data` blob NOT NULL,
  `expired_at` datetime NOT NULL,
  PRIMARY KEY (`key`)
)
```

**Comment by wuhan005** [comment]
不过现在已经支持存储 Session 至 Redis 了，目前线上也是这样做的。

**Comment by hdm9527** [comment]
> 不过现在已经支持存储 Session 至 Redis 了，目前线上也是这样做的。

我先跑起来看看，有装Redis

**Comment by hdm9527** [comment]
> 

谢谢，跑起来了

**Comment by hdm9527** [comment]
> 这是 Flamego Session 中间件的一个老问题了。 在使用 MySQL 数据库存储 Session 时不会自动创建表，需要手动执行如下语句创建：
> 
> ```sql
> CREATE TABLE `sessions` (
>   `key` varchar(255) NOT NULL,
>   `data` blob NOT NULL,
>   `expired_at` datetime NOT NULL,
>   PRIMARY KEY (`key`)
> )
> ```

跑起来了，谢谢
