### ISSUE TITLE
大佬可以给一份配置文档吗，自己部署的注册没反应

### ISSUE THREAD

**Issue by hdm9527** [NekoWheel/NekoBox#26]
那个UPTRACE_DSN也不知道是啥，后端也没有其他的报错信息
![image](https://user-images.githubusercontent.com/39702328/204318806-a5744ec8-f3c2-4aa7-ae36-1ed2da79343f.png)
前端只有异步响应错误
![image](https://user-images.githubusercontent.com/39702328/204319189-cbaebe2b-76b0-4591-83b2-9de07246eef1.png)
配置文件那个七牛云是必须的吗
![image](https://user-images.githubusercontent.com/39702328/204319592-19a2338c-525a-4ec8-81c4-05a66e293d2c.png)

**Comment by hdm9527** [comment]
哪些配置是必须的

**Comment by wuhan005** [comment]
我看下把一些功能设置成可选是否开启的。
七牛云的 AKSK 是用于接七牛的内容审查的，Uptrace 是用来做链路追踪的，这些功能应该被做成可配置的。

**Comment by hdm9527** [comment]
> 我看下把一些功能设置成可选是否开启的。 七牛云的 AKSK 是用于接七牛的内容审查的，Uptrace 是用来做链路追踪的，这些功能应该被做成可配置的。

点击注册没有反应是哪里的原因

**Comment by wuhan005** [comment]
可以 F12 看下请求，猜测是 reCAPTCHA 验证码的问题，来源有添加 `localhost` 嘛？

**Comment by hdm9527** [comment]
> 可以 F12 看下请求，猜测是 reCAPTCHA 验证码的问题，来源有添加 `localhost` 嘛？

还是这个
![image](https://user-images.githubusercontent.com/39702328/204540281-6b119c38-d0ec-4152-8b7f-0c74217d7663.png)
点击注册也没有发起网络请求
![image](https://user-images.githubusercontent.com/39702328/204539164-0c4c1b9d-a962-4cb6-baf0-4b252747f8a9.png)
reCAPTCHA配置
![image](https://user-images.githubusercontent.com/39702328/204539279-2800b6c6-8d11-49b7-be7b-3001855e9b86.png)
[编译的linux-amd64版本](https://rn.37373.xyz/d/local/NekoBox?sign=jIfCOz_ahNWyKbpkH7okDShXExo4NuiVzfPQh50-Fds=:0)

**Comment by wuhan005** [comment]
emmm 这就比较奇怪了，我感觉还是 reCAPTCHA 加载的问题。

或者可以试试换成 reCAPTCHA 的测试 Key（放通所有验证）：
```
Site key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
Secret key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
```
来测试看下是否还有问题。

**Comment by hdm9527** [comment]
> emmm 这就比较奇怪了，我感觉还是 reCAPTCHA 加载的问题。
> 
> 或者可以试试换成 reCAPTCHA 的测试 Key（放通所有验证）：
> 
> ```
> Site key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
> Secret key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
> ```
> 
> 来测试看下是否还有问题。

谢谢大佬，可以用了，reCAPTCHA是哪里设置错了吗？可以给个reCAPTCHA的设置模板吗，第一次用reCAPTCHA

**Comment by wuhan005** [comment]
这是我本地调试时用的，也就是上述的测试 Key，线上环境用的是自己的。
<img width="424" alt="image" src="https://user-images.githubusercontent.com/12731778/205483532-5630f850-1f94-4c87-919e-ccccae24da17.png">

以及这个是 reCAPTCHA 控制台的设置。
<img width="713" alt="image" src="https://user-images.githubusercontent.com/12731778/205483602-949df172-acd8-4d04-b233-5d25528063df.png">

我猜测你上面有问题应该还是配置的域名和实际访问的 URL 中的域名没对上，这种情况下 reCAPTCHA 是会直接用不了但是却不报任何错误。

**Comment by hdm9527** [comment]
> 这是我本地调试时用的，也就是上述的测试 Key，线上环境用的是自己的。 <img alt="image" width="424" src="https://user-images.githubusercontent.com/12731778/205483532-5630f850-1f94-4c87-919e-ccccae24da17.png">
> 
> 以及这个是 reCAPTCHA 控制台的设置。 <img alt="image" width="713" src="https://user-images.githubusercontent.com/12731778/205483602-949df172-acd8-4d04-b233-5d25528063df.png">
> 
> 我猜测你上面有问题应该还是配置的域名和实际访问的 URL 中的域名没对上，这种情况下 reCAPTCHA 是会直接用不了但是却不报任何错误。

谢谢大佬，我再找找问题，我那里填的是二级域名（按理说三级域名也会顺带注册），类型是复选框（不知道是不是这个的原因）
![image](https://user-images.githubusercontent.com/39702328/205483859-7d8f7244-d129-4098-82f5-483f028a2216.png)
![image](https://user-images.githubusercontent.com/39702328/205483877-a96df6f2-b9fa-4fdd-82b4-9566fe3d8a79.png)

**Comment by hdm9527** [comment]
> 这是我本地调试时用的，也就是上述的测试 Key，线上环境用的是自己的。 <img alt="image" width="424" src="https://user-images.githubusercontent.com/12731778/205483532-5630f850-1f94-4c87-919e-ccccae24da17.png">
> 
> 以及这个是 reCAPTCHA 控制台的设置。 <img alt="image" width="713" src="https://user-images.githubusercontent.com/12731778/205483602-949df172-acd8-4d04-b233-5d25528063df.png">
> 
> 我猜测你上面有问题应该还是配置的域名和实际访问的 URL 中的域名没对上，这种情况下 reCAPTCHA 是会直接用不了但是却不报任何错误。

reCAPTCHA 类型选错了，要选隐式类型，非常感谢大佬
