### ISSUE TITLE
更新背景和头像时报错

### ISSUE THREAD

**Issue by hdm9527** [NekoWheel/NekoBox#28]
![image](https://user-images.githubusercontent.com/39702328/205487476-409faba2-ce98-4e53-b19c-8841cfafddc8.png)
换一个bucket还是报错
![image](https://user-images.githubusercontent.com/39702328/205487520-029d687d-aa55-42fd-8ceb-7cc6203dca59.png)
配置文件
![image](https://user-images.githubusercontent.com/39702328/205487637-ac09bc12-0d46-4592-bfc7-ec32fc929650.png)

**Comment by wuhan005** [comment]
`aliyun_bucket` 去掉后面的 `.oss-cn-shanghai.aliyuncs.com`

**Comment by hdm9527** [comment]
> `aliyun_bucket` 去掉后面的 `.oss-cn-shanghai.aliyuncs.com`

好的
