### ISSUE TITLE
domain of the link in mail is fixed

### ISSUE THREAD

**Issue by Akegarasu** [NekoWheel/NekoBox#36]
[internal/mail](https://github.com/NekoWheel/NekoBox/blob/master/internal/mail/mail.go#L23)

**Comment by wuhan005** [comment]
Sorry for the slow response.

The domain will be loaded from the `external_url` field in the configuration file.

https://github.com/NekoWheel/NekoBox/commit/f83b50827f6f44ae27ec20dc4f04d11c2d7a46a7
