### ISSUE TITLE
希望可以加上直连兜底的选项

### ISSUE THREAD

**Issue by moosetk** [NekoWheel/NekoBox#47]
当我想要用 代理黑名单的时候（比如只代理  geosite:gfw ），  好像怎么设置路由规则都不能实现

**Comment by wuhan005** [comment]
唔。。有点没懂。
目前 NekoBox 是已经关站了的。

**Comment by wuhan005** [comment]
又是一个走错地方的：https://github.com/MatsuriDayo/NekoBoxForAndroid/issues
