### ISSUE TITLE
有无大佬打包armv7 armv8 x86 docker镜像，眼神暗示

### ISSUE THREAD

**Issue by SoraKasvgano** [NekoWheel/NekoBox#52]
有无大佬打包armv7 armv8 x86镜像，眼神暗示、

偷懒。webp

**Comment by wuhan005** [comment]
https://github.com/MatsuriDayo/NekoBoxForAndroid 走错地方了？

**Comment by SoraKasvgano** [comment]
> https://github.com/MatsuriDayo/NekoBoxForAndroid 走错地方了？

没有没有，想在本地树莓派局域网上搭建提问箱 2333

**Comment by wuhan005** [comment]
拿我的树莓派建了个 self-hosted runner 跑的，可以试一下：
https://github.com/NekoWheel/NekoBox/pkgs/container/nekobox
