### ISSUE TITLE
后续能自定义图床吗

### ISSUE THREAD

**Issue by tamakyi** [NekoWheel/NekoBox#55]
作者您好，看到网站现在把带图提问的功能加上了，使用以后感觉很棒，但是因为用的是cf的r2，实际使用中有时候会很慢。目前我在用源码搭建自己的提问箱，想问下后续作者有新增自定义图床或者oss的相关配置的计划吗？

**Comment by wuhan005** [comment]
> 作者您好，看到网站现在把带图提问的功能加上了，使用以后感觉很棒，但是因为用的是cf的r2，实际使用中有时候会很慢。目前我在用源码搭建自己的提问箱，想问下后续作者有新增自定义图床或者oss的相关配置的计划吗？

因为 Cloudflare R2 是 S3 Compatible 的，所以是直接使用 AWS S3 官方的 Go SDK 进行接入。

同理阿里云 OSS 也是兼容 S3 协议的：https://help.aliyun.com/zh/oss/developer-reference/use-amazon-s3-sdks-to-access-oss?#section-sp0-q7h-dvj 

但根据文档来看，貌似阿里云魔改了一些参数，可以对照着文档修改此处的代码来适配 OSS。https://github.com/NekoWheel/NekoBox/blob/master/route/question/page.go#L287-L295

**Comment by tamakyi** [comment]
> > 作者您好，看到网站现在把带图提问的功能加上了，使用以后感觉很棒，但是因为用的是cf的r2，实际使用中有时候会很慢。目前我在用源码搭建自己的提问箱，想问下后续作者有新增自定义图床或者oss的相关配置的计划吗？
> 
> 因为 Cloudflare R2 是 S3 Compatible 的，所以是直接使用 AWS S3 官方的 Go SDK 进行接入。
> 
> 同理阿里云 OSS 也是兼容 S3 协议的：https://help.aliyun.com/zh/oss/developer-reference/use-amazon-s3-sdks-to-access-oss?#section-sp0-q7h-dvj
> 
> 但根据文档来看，貌似阿里云魔改了一些参数，可以对照着文档修改此处的代码来适配 OSS。https://github.com/NekoWheel/NekoBox/blob/master/route/question/page.go#L287-L295

 好的，感谢答复！

**Comment by tamakyi** [comment]
我看到有提到`/conf/share.yaml`这个文件，但是在conf目录下并未找到，这个文件是否必须的。以及在app.sample.ini中没有找到配置S3 api的选项，能参考下如何配置吗？

**Comment by tamakyi** [comment]
> 我看到有提到`/conf/share.yaml`这个文件，但是在conf目录下并未找到，这个文件是否必须的。以及在app.sample.ini中没有找到配置S3 api的选项，能参考下如何配置吗？

没事了，上传成功了。
