### ISSUE TITLE
如何让别人也可访问

### ISSUE THREAD

**Issue by mkbk-with-circle** [NekoWheel/NekoBox#59]
首先，抱歉我对网络配置完全不了解，所以您可能觉得我以下的问题非常愚蠢！
<img width="686" alt="截屏2024-09-13 01 08 10" src="https://github.com/user-attachments/assets/c7d06951-adb5-41ba-8523-3e9a3ca14820">
<img width="691" alt="截屏2024-09-13 01 09 05" src="https://github.com/user-attachments/assets/cb091506-aada-4773-b1cf-bfa0505e5b6f">
是这样的，我现在基本上配置好了，但是对于ini配置文件有一个改动即在[app]处加了一行“external_url = "http://localhost:3000"  # 本地开发环境的 URL”，否则会无法运行并且报错：“ ./NekoBox web
FATA[0000] Failed to start application                   error="load configuration: app.external_url is required"”
然后问了gpt之后它让我写了一个本地的网址：“http://localhost:3000”
然后现在我就只能通过本地的这个网来访问了
所以我的问题就是：
**一，我该如何配置才能将这个东西分享给其他人**
二，为什么我的分享码没有图片
<img width="1512" alt="截屏2024-09-13 01 22 21" src="https://github.com/user-attachments/assets/9b2bf768-f48b-4d9e-a15b-c68ea484813f">
感谢大佬答疑解惑！！！

**Comment by wuhan005** [comment]
1. `external_url` 中配置的是站点对外的 URL。如果你需要分享给他人，如果部署在公网上，别人是通过域名访问的，那么这里就填写公网域名 URL。如果别人是通过内网访问，那么这里填写的就是站点的内网 IP。
2. 关于分享码没有图片，可以浏览器打开 F12 看一下控制台报错，头像图片不显示应该是你的阿里云 OSS 需要配置同源 CORS 策略，具体来说就是你要加响应头允许 `http://localhost:8080` 到 `https://oss-cn-beijing.aliyuncs.com/` 的跨域访问。背景图片不显示，这个背景图是存储在我的 Cloudflare R2 上的，做了来源限制，所以加载不出来。我看之后给迁到公共图床上。

**Comment by mkbk-with-circle** [comment]
> 1. `external_url` 中配置的是站点对外的 URL。如果你需要分享给他人，如果部署在公网上，别人是通过域名访问的，那么这里就填写公网域名 URL。如果别人是通过内网访问，那么这里填写的就是站点的内网 IP。
> 2. 关于分享码没有图片，可以浏览器打开 F12 看一下控制台报错，头像图片不显示应该是你的阿里云 OSS 需要配置同源 CORS 策略，具体来说就是你要加响应头允许 `http://localhost:8080` 到 `https://oss-cn-beijing.aliyuncs.com/` 的跨域访问。背景图片不显示，这个背景图是存储在我的 Cloudflare R2 上的，做了来源限制，所以加载不出来。我看之后给迁到公共图床上。

非常感谢🥹🥹🥹！！最后一个小问题，如果想要部署在公网，那我是不是要花钱去买个域名这样的？🤔

**Comment by wuhan005** [comment]
> > 1. `external_url` 中配置的是站点对外的 URL。如果你需要分享给他人，如果部署在公网上，别人是通过域名访问的，那么这里就填写公网域名 URL。如果别人是通过内网访问，那么这里填写的就是站点的内网 IP。
> > 2. 关于分享码没有图片，可以浏览器打开 F12 看一下控制台报错，头像图片不显示应该是你的阿里云 OSS 需要配置同源 CORS 策略，具体来说就是你要加响应头允许 `http://localhost:8080` 到 `https://oss-cn-beijing.aliyuncs.com/` 的跨域访问。背景图片不显示，这个背景图是存储在我的 Cloudflare R2 上的，做了来源限制，所以加载不出来。我看之后给迁到公共图床上。
> 
> 非常感谢🥹🥹🥹！！最后一个小问题，如果想要部署在公网，那我是不是要花钱去买个域名这样的？🤔

部署在公网需要花钱去买一台云服务器，域名不是必要条件。没有域名的情况下可以配置成让别人通过服务器 IP 访问。

**Comment by mkbk-with-circle** [comment]
非常感谢您的回答！这对我帮助很大！祝您生活愉快！

**Comment by mkbk-with-circle** [comment]
<img width="1512" alt="截屏2024-09-13 13 10 28" src="https://github.com/user-attachments/assets/eb0623fd-347d-41a5-a550-35afba4b71e6">
啊啊啊对不起我又来了
我试用了一个小服务器，然后如界面所示
<img width="1512" alt="截屏2024-09-13 13 11 17" src="https://github.com/user-attachments/assets/3f98035b-b632-49d9-bce7-8e1265c085e9">
我把external_url写为http://82.156.108.92之后运行但是始终都是另一个页面：
<img width="1512" alt="截屏2024-09-13 13 12 06" src="https://github.com/user-attachments/assets/3f885056-c065-4e57-ba86-61b19e571c65">
请问这个是因为服务器的原因莫🤧🤧🤧🤧麻烦您嘞

**Comment by wuhan005** [comment]
这是在腾讯云上开了台轻量服务器然后选择了预装 WordPress 吗？
可以仅安装 Linux 系统，SSH 连接上去后输入命令启动 NekoBox，由于 NekoBox 的默认是监听 `3000` 端口。你可能需要在服务器 IP 后加上端口号，才能访问到 NekoBox 的服务。

**Comment by mkbk-with-circle** [comment]
> 这是在腾讯云上开了台轻量服务器然后选择了预装WordPress吗？ 可以只安装Linux系统，SSH连接上去后输入命令启动NekoBox，由于NekoBox的默认是监听`3000`端口。你可能需要在服务器IP后加上端口号，就可以访问NekoBox的服务。

哇塞您说的很对！我就是在腾讯云上打开的轻量服务器然后就预装了WordPress，对于您说的“SSH连接上去后输入命令启动NekoBox”，那我是还需要再这个服务器上下载整个项目吗然后在服务器上启动吗？

**Comment by wuhan005** [comment]
嗯对，最简单直接的方法就是在服务器上 `git clone` 下载下来，然后**在服务器上**编译，再按你上面的流程写好配置文件启动即可。

**Comment by mkbk-with-circle** [comment]
好！我今晚试试！感谢！
